In [1]:
import torch
import pandas
import numpy
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

2.8.0


# Intro to Tensors

## Creating Tensors

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [6]:
# Get the number within a tensto (only works with one-element tensors)
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
MATRIX = torch.tensor(
    [
        [5,6],
        [7,8]
    ]
)

MATRIX

tensor([[5, 6],
        [7, 8]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
# Tensor

TENSOR = torch.tensor(
    [ # vector made up of 2d-matricies
        [ #2d matrix = vector made up of one-dim vectors
            [1,2,3],
            [4,5,6]
        ],
        [ #2d matrix = vector made up of one-dim vectors
            [7,8,9],
            [10,11,12]
        ]
    ]
)

TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [ ]:
TENSOR.ndim
# Depth = 2, Height = 2, Width = 3

3

In [ ]:
TENSOR.shape
# Each number from left to right is associated with the brackets from outermost to innermost.

torch.Size([2, 2, 3])

### Random Tensors

In [21]:
random_tensor = torch.rand(3,4)
random_tensor, random_tensor.dtype, random_tensor.shape

(tensor([[0.7270, 0.5133, 0.9241, 0.2069],
         [0.3756, 0.8264, 0.4569, 0.3538],
         [0.3711, 0.3331, 0.7353, 0.7717]]),
 torch.float32,
 torch.Size([3, 4]))

In [ ]:
# Create a tensor to mimic the data format of an image
random_image_tensor = torch.rand(size=(3, 244, 244)) # color channel, height, width
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([3, 255, 255]), 3)

### Zeros and Ones

In [25]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Range and Alike

In [27]:
zero_to_ten = torch.arange(start=0, end=11, step=1)
zero_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [ ]:
float_32_tensor = torch.tensor([3, 6, 9], 
                                dtype=None, #default is torch.float32
                                device=None, #default is cpu (I think)
                                requires_grad=False #if true any operations performed on the tensor is recorded
)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.int64, device(type='cpu'))

In [ ]:
float_16_tensor = torch.tensor([3, 6, 9], dtype=torch.float16, device=None, requires_grad=False)

### Information From Tensors

We've seen these before but three of the most common attributes you'll want to find out about tensors are:

* shape - what shape is the tensor? (some operations require specific shape rules)
* dtype - what datatype are the elements within the tensor stored in?
* device - what device is the tensor stored on? (usually GPU or CPU)

In [32]:
some_tensor = torch.rand(3, 4)

print(some_tensor)
print('Shape:', some_tensor.shape)
print('DType:', some_tensor.dtype)
print('Device:', some_tensor.device)

tensor([[0.0227, 0.1026, 0.0695, 0.8421],
        [0.0375, 0.8137, 0.2404, 0.0877],
        [0.0112, 0.6010, 0.0863, 0.8049]])
Shape: torch.Size([3, 4])
DType: torch.float32
Device: cpu


### Manipulating tensors (tensor operations)

In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.

These operations are often a wonderful dance between:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

And that's it. Sure there are a few more here and there but these are the basic building blocks of neural networks.

Stacking these building blocks in the right way, you can create the most sophisticated of neural networks (just like lego!).

In [33]:
torch.backends.mps.is_available() # Note this will print false if you're not running on a Mac

True