In [105]:
import torch
import pandas
import numpy as np
import matplotlib.pyplot as plt

In [106]:
print(torch.__version__)

2.8.0


# Intro to Tensors

## Creating Tensors

In [107]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [108]:
scalar.ndim

0

In [109]:
# Get the number within a tensto (only works with one-element tensors)
scalar.item()

7

In [110]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [111]:
vector.ndim

1

In [112]:
vector.shape

torch.Size([2])

In [113]:
MATRIX = torch.tensor(
    [
        [5,6],
        [7,8]
    ]
)

MATRIX

tensor([[5, 6],
        [7, 8]])

In [114]:
MATRIX.ndim

2

In [115]:
MATRIX.shape

torch.Size([2, 2])

In [116]:
# Tensor

TENSOR = torch.tensor(
    [ # vector made up of 2d-matricies
        [ #2d matrix = vector made up of one-dim vectors
            [1,2,3],
            [4,5,6]
        ],
        [ #2d matrix = vector made up of one-dim vectors
            [7,8,9],
            [10,11,12]
        ]
    ]
)

TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [117]:
TENSOR.ndim
# Depth = 2, Height = 2, Width = 3

3

In [118]:
TENSOR.shape
# Each number from left to right is associated with the brackets from outermost to innermost.

torch.Size([2, 2, 3])

### Random Tensors

In [119]:
random_tensor = torch.rand(3,4)
random_tensor, random_tensor.dtype, random_tensor.shape

(tensor([[0.4754, 0.4414, 0.2275, 0.4204],
         [0.5921, 0.7143, 0.7107, 0.2309],
         [0.1167, 0.0386, 0.8856, 0.6595]]),
 torch.float32,
 torch.Size([3, 4]))

In [120]:
# Create a tensor to mimic the data format of an image
random_image_tensor = torch.rand(size=(3, 244, 244)) # color channel, height, width
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([3, 244, 244]), 3)

### Zeros and Ones

In [121]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [122]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Range and Alike

In [123]:
zero_to_ten = torch.arange(start=0, end=11, step=1)
zero_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [124]:
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [125]:
float_32_tensor = torch.tensor([3, 6, 9], 
                                dtype=None, #default is torch.float32
                                device=None, #default is cpu (I think)
                                requires_grad=False #if true any operations performed on the tensor is recorded
)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.int64, device(type='cpu'))

In [126]:
float_16_tensor = torch.tensor([3, 6, 9], dtype=torch.float16, device=None, requires_grad=False)

### Information From Tensors

We've seen these before but three of the most common attributes you'll want to find out about tensors are:

* shape - what shape is the tensor? (some operations require specific shape rules)
* dtype - what datatype are the elements within the tensor stored in?
* device - what device is the tensor stored on? (usually GPU or CPU)

In [127]:
some_tensor = torch.rand(3, 4)

print(some_tensor)
print('Shape:', some_tensor.shape)
print('DType:', some_tensor.dtype)
print('Device:', some_tensor.device)

tensor([[0.6908, 0.3495, 0.1075, 0.8406],
        [0.0355, 0.6141, 0.6073, 0.3329],
        [0.7014, 0.0778, 0.7845, 0.0339]])
Shape: torch.Size([3, 4])
DType: torch.float32
Device: cpu


### Manipulating tensors (tensor operations)

In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.

These operations are often a wonderful dance between:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

And that's it. Sure there are a few more here and there but these are the basic building blocks of neural networks.

Stacking these building blocks in the right way, you can create the most sophisticated of neural networks (just like lego!).

In [128]:
# Arithmetic Add
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [129]:
#Arithmetic Multiply
tensor * 10

tensor([10, 20, 30])

In [130]:
tensor

tensor([1, 2, 3])

In [131]:
#Subtraction + reassignment
tensor -= 10
tensor

tensor([-9, -8, -7])

In [132]:
tensor += 10
tensor

tensor([1, 2, 3])

In [133]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [134]:
tensor

tensor([1, 2, 3])

In [135]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


### Matric Multiplication

In [136]:
tensor = torch.tensor([1,2,3])
tensor.shape

torch.Size([3])

In [137]:
#Again element-wise
tensor * tensor

tensor([1, 4, 9])

In [138]:
#Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [139]:
#Another syntac for Matrix multiplication
tensor @ tensor

tensor(14)

You will observe how much faster it is to do matrix multiplication with torch than with a for loop.

Let's compare the following:
1. For loop run time
2. Numpy run time
3. PyTorch run time

#### For Loop

In [140]:
%%time

value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: user 203 μs, sys: 243 μs, total: 446 μs
Wall time: 259 μs


tensor(14)

#### NumPy

In [143]:
vector = np.array([1,2,3])

In [145]:
%%time
vector @ vector

CPU times: user 24 μs, sys: 212 μs, total: 236 μs
Wall time: 844 μs


np.int64(14)

#### Torch

In [146]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 82 μs, sys: 30 μs, total: 112 μs
Wall time: 111 μs


tensor(14)

In [148]:
tensor.device

device(type='cpu')

#### Shape Errors

In [151]:
tensor_A = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
], dtype=torch.float32)

tensor_B = torch.tensor([
    [7,  8],
    [9, 10],
    [5, 11]
], dtype=torch.float32)

In [152]:
tensor_A @ tensor_B

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
#Transpose
trans_tensor_B = tensor_B.T
print(trans_tensor_B)

tensor([[ 7.,  9.,  5.],
        [ 8., 10., 11.]])


In [154]:
tensor_A @ tensor_B.T

tensor([[ 23.,  29.,  27.],
        [ 53.,  67.,  59.],
        [ 83., 105.,  91.]])

In [ ]:
torch.manual_speed(42)
linear = torch.nn.Linear(in_feature=2,
                         out_features=6)
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput s")